### PR TITLE
Query results can be dragged

### PR DESCRIPTION
**Pull request by jrnorth**

### CODE REVIEW

**Comment by jrnorth** [comment]
build now

**Review by andrewkfiedler — APPROVED** [review]

**Comment by jrnorth** [comment]
build now

**Review by pvargas — APPROVED** [review]

**Review by alexabird — APPROVED** [review]

**Comment by alexabird** [comment]
build now

**Comment by alexabird** [comment]
did a preliminary hero and needs a `yarn format -w`, otherwise looks good 💯

**Comment by jrnorth** [comment]
build now

**Comment by jlcsmith** [comment]
Hero was successful

**Pull request merged**
