### PR TITLE
Support exporting deleted items with Export As interaction

### PR DESCRIPTION
**Pull request by sgalla**

### CODE REVIEW

**Comment by sgalla** [comment]
build now

**Comment by sgalla** [comment]
build now

**Review by jlcsmith — APPROVED** [review]

**Review by pvargas — APPROVED** [review]

**Comment by andrewkfiedler** [comment]
Is there a downside to adding a metacard.tags * to those cql filters?  It might be more simple.  Something like:
```
 {
              type: 'ILIKE',
              property: '"metacard-tags"',
              value: '*',
}
```

**Comment by andrewkfiedler** [comment]
> Is there a downside to adding a metacard.tags * to those cql filters? It might be more simple. Something like:
> 
> ```
>  {
>               type: 'ILIKE',
>               property: '"metacard-tags"',
>               value: '*',
> }
> ```

We do something like this to ensure we get a result back when refreshing result data:
https://github.com/codice/ddf-ui/blob/master/ui-frontend/packages/catalog-ui-search/src/main/webapp/js/model/QueryResult.ts#L200

**Comment by sgalla** [comment]
build now

**Comment by zkirksey** [comment]
Hero was successful!

**Pull request merged**
