### PR TITLE
Update query status dropdown and sources popover

### PR DESCRIPTION
**Pull request by samuelechu**
Partial forward port of https://github.com/codice/ddf-ui/pull/578.

This additionally sets a max height of 50vh for both the sources and query status popover.
image
image

### CODE REVIEW

**Review by jordanwilking — APPROVED** [review]

**Comment by jordanwilking** [comment]
build now

**Comment by jordanwilking** [comment]
Already reviewed and heroed as part of #578.

The code was slightly different, so I verified the functionality again
image
image

**Comment by jordanwilking** [comment]
Looks like we just need to remove a these unused imports
```
[2021-05-05T17:24:48.856Z] [ERROR] src/main/webapp/component/result-selector/query-feed.tsx(3,1): error TS6133: 'Dropdown' is declared but its value is never read.

[2021-05-05T17:24:48.856Z] [ERROR] src/main/webapp/component/result-selector/query-feed.tsx(5,1): error TS6133: 'BetterClickAwayListener' is declared but its value is never read.
```

**Comment by samuelechu** [comment]
build now

**Comment by jordanwilking** [comment]
build now

**Pull request merged**
