### PR TITLE
Update export transform to take into account phonetics and spellcheck

### PR DESCRIPTION
**Pull request by andrewkfiedler**
- Updates the frontend to pass these along, and the backend to set them appropriately

### CODE REVIEW

**Comment by andrewkfiedler** [comment]
build now

**Review by jlcsmith — APPROVED** [review]

**Review by vinamartin — APPROVED** [review]

**Comment by andrewkfiedler** [comment]
build now

**Comment by andrewkfiedler** [comment]
build now

**Comment by andrewkfiedler** [comment]
build now

**Comment by jordanwilking** [comment]
@andrewkfiedler How could we test this one?

**Comment by andrewkfiedler** [comment]
> @andrewkfiedler How could we test this one?

I think we're okay to merge given the hero succeeded on https://github.com/codice/ddf-ui/pull/563

**Pull request merged**
