### PR TITLE
Update cesium programmatic zoom functions to prevent render issues

### PR DESCRIPTION
**Pull request by andrewkfiedler**
- The old zoom in could go too far and cause render issues with cesium.  This puts a limit on the zoom of being at least 2 above the terrain in terms of height.

### CODE REVIEW

**Review by maiiiiiiii — APPROVED** [review]

**Comment by maiiiiiiii** [comment]
hero successful! 
https://github.com/codice/ddf-ui/assets/58529232/e0d7bf29-df77-4965-af6f-db63c9d1c96c

**Comment by jlcsmith** [comment]
build now

**Review by pvargas — APPROVED** [review]

**Comment by jlcsmith** [comment]
build now

**Comment by jlcsmith** [comment]
build now

**Review by jlcsmith — APPROVED** [review]

**Pull request merged**
