### PR TITLE
fix unreadable search results when attribute is updated

### PR DESCRIPTION
**Pull request by zack-leidos**
**What does this PR do, and why?**
The purpose of this PR is to fix a bug. When a user updates a result attribute and clicks on the unfocused (hidden) results tab, the items in the tab become unreadable. The PR addresses the issue.

**How should this be tested?**
Use the drop a Jar method to test the PR on an MIO

In the frontend application, upload two files in the Create section in the left menu bar
Make sure Results and Inspector windows are together as tabs in one window
Go to the Search function in the left side menu bar
Search for Fast data source
Click on one of the files you uploaded, then go to Inspector
Modify releasability and click save
Go back to the Results tab
You should see the results are unreadable then they appear readable (before, the results would remain unreadable)

**PR Definition of Done**
See that results are readable when the result attribute is changed.

### CODE REVIEW

**Comment by LiamYokoyama** [comment]
Successfully Heroed on my MIO.

**Review by andrewkfiedler — APPROVED** [review]

**Review by alexabird — APPROVED** [review]

**Comment by LiamYokoyama** [comment]
Successful hero on my MIO.

**Comment by jlcsmith** [comment]
build now

**Comment by jlcsmith** [comment]
build now

**Comment by jlcsmith** [comment]
build now

**Pull request merged**
