### PR TITLE
Add custom hover extension point for histogram visual

### PR DESCRIPTION
**Pull request by sgalla**
* Add an extension point to customize the font color, background color, and additional content in the hover tooltip for histogram visual.
* Update the inspector title add on extension point to also display in the results list. This helps keep the UI more consistent.

### CODE REVIEW

**Comment by sgalla** [comment]
build now

**Comment by sgalla** [comment]
build now

**Comment by sgalla** [comment]
build now

**Review by jlcsmith — APPROVED** [review]

**Review by andrewkfiedler — APPROVED** [review]
That's a big dependency jump 🎉

**Pull request merged**
