### PR TITLE
Adds a new profile to make installing into ddf easier

### PR DESCRIPTION
**Pull request by andrewkfiedler**
- Now it's as simple as two commands:
feature:repo-add mvn:org.codice.ddf.search/intrigue-ui-app/{version}/xml/features
feature:install ddf-ui

### CODE REVIEW

**Review by jordanwilking — APPROVED** [review]

**Comment by jordanwilking** [comment]
🌐  Hero Successful  🌐 

#### Steps

1. Built ddf
2. Built ddf:ui
3. Ran ddf
4. In karaf console,  executed `feature:repo-add mvn:org.codice.ddf.search/intrigue-ui-app/5.0.3-SNAPSHOT/xml/features`
5. In karaf console, executed `feature:install ddf-ui`
6. Verified that major routes loaded up.

**Review by jlcsmith — APPROVED** [review]

**Comment by jordanwilking** [comment]
build now

**Comment by jordanwilking** [comment]
build now

**Comment by jordanwilking** [comment]
build now

**Pull request merged**
