### PR TITLE
G-9437 Include the cacheId for table exports

### PR DESCRIPTION
**Pull request by jrnorth**
Downstream projects need the cacheId, since they may have sources that cache results by the ID.

Forward port of https://github.com/codice/ddf/pull/6593

### CODE REVIEW

**Comment by jrnorth** [comment]
build now

**Review by shaundmorris — APPROVED** [review]

**Review by samuelechu — APPROVED** [review]

**Comment by shaundmorris** [comment]
build now

**Comment by LinkMJB** [comment]
build now

**Comment by jrnorth** [comment]
build now

**Pull request merged**
