### PR TITLE
Update source selector / sources button

### PR DESCRIPTION
**Pull request by samuelechu**
Changes sources button to display sources on click instead of on hover, and adds scrolling to the popover. 
image

Updates appearance of source selector based on this mockup
image

old: 
image

updated:
image

### CODE REVIEW

**Review by jlcsmith — APPROVED** [review]

**Comment by jlcsmith** [comment]
build now

**Comment by samuelechu** [comment]
Will need to pass a function to the custom sources page component that updates the position of the popover (custom sources page in downstream projects may dynamically render content)

**Review by jordanwilking — APPROVED** [review]

**Comment by jordanwilking** [comment]
build now

**Comment by jordanwilking** [comment]
🍿 Hero Successful 🍿 

#### Steps

1. Opened source selector and verified the style changes

    image

2. Reduced the window size and verified that the source popover handles resizing well - it repositions and then adds a scroll bar when too small.

    image

3. Verified that sources are displayed on click, not on hover
4. Throttled the performance in chrome dev tools and verified there wasn't any of the previous weirdness that the hover state was experiencing

**Comment by jordanwilking** [comment]
build now

**Pull request merged**
